services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./vaultwarden:/data:rw
    ports:
      - 8200:80
    restart: unless-stopped 


